---
# role: ansible-role-networkmanager
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: alpine-networkmanager
    image: "jomrr/molecule-alpine:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: amazon-networkmanager
    image: "jomrr/molecule-amazonlinux:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: arch-networkmanager
    image: "jomrr/molecule-archlinux:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: centos-networkmanager
    image: "jomrr/molecule-centos:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: debian-networkmanager
    image: "jomrr/molecule-debian:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: fedora-networkmanager
    image: "jomrr/molecule-fedora:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: opensuse-networkmanager
    image: "jomrr/molecule-opensuse:15"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: tumbleweed-networkmanager
    image: "jomrr/molecule-opensuse:tumbleweed"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: oracle-networkmanager
    image: "jomrr/molecule-oraclelinux:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ubuntu-networkmanager
    image: "jomrr/molecule-ubuntu:latest"
    command: ~
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        networkmanager_role_enabled: true
verifier:
  name: ansible
