---
# role: ansible-role-networkmanager
# file: molecule/vbox/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: jomrr
  provider:
    name: vb
    type: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: alpine-networkmanager
    box: "generic/alpine312"
    cpus: 2
    memory: 2048
  - name: amazon-networkmanager
    box: "bento/amazonlinux-2"
    cpus: 2
    memory: 2048
  - name: arch-networkmanager
    box: "archlinux/archlinux"
    cpus: 2
    memory: 2048
  - name: centos-networkmanager
    box: "centos/8"
    cpus: 2
    memory: 2048
  - name: debian-networkmanager
    box: "debian/bullseye64"
    cpus: 2
    memory: 2048
  - name: fedora-networkmanager
    box: "fedora/33-cloud-base"
    cpus: 2
    memory: 2048
  - name: opensuse-networkmanager
    box: "generic/opensuse15"
    cpus: 2
    memory: 2048
  - name: oracle-networkmanager
    box: "generic/oracle8"
    cpus: 2
    memory: 2048
  - name: ubuntu-networkmanager
    box: "ubuntu/focal64"
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        networkmanager_role_enabled: true
verifier:
  name: ansible
